name: CI
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: null

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Copy Files to Deployment
        run: 'Xcopy /e /i /y * C:\Deployment\'
      - name: Run TOSCA Test
        run: C:\GitHub\ToscaCIClient\ToscaCIClient.exe -m distributed -c "CITestExecutionConfiguration.xml"
      - name: Attach the Report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: Results.xml
          path: 'C:\GitHub\Result\Results.xml'
      - name:Test Reporter
        uses: dorny/test-reporter@v1.4.3
	with:
	  name: Test1
	  path: Results.xml
	  reporter: java -junit
