name: CI
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: null

jobs:
  build:
    runs-on: self-hosted
    steps:
      image: alpine:latest

stages:
  - build
  - deploy
  - test

build:
  stage: build
  script: 
    - echo 'Build complete'

deploy:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - echo 'App deployed'
  artifacts:
    paths:
      - public
  only:
    - master

tosca:
  stage: test
  script:
    - cd C:\GitHub\ToscaCIClient\
    - .\ToscaCIClient.exe -m distributed -c "CITestExecutionConfiguration.xml"
    - cp C:\GitHub\ToscaCIResults\result.xml $CI_PROJECT_DIR\ToscaCIResults.xml
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR\ToscaCIResults.xml
  tags: 
    - toscaci
