name: CI
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: null

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Copy Files to Deployment
        run: 'Xcopy /e /i /y * C:\Deployment\'
      - name: Run TOSCA Test
        run: 'C:\GitHub\ToscaCIClient\ToscaCIClient.exe -m distributed -c "C:\GitHub\TOSCACIClient\CITestExecutionConfiguration.xml" -r "C:\GitHub\Result\Results.xml"'
